apiVersion: v1
kind: Service
metadata:
  labels:
    app: polaris
  name: polaris
spec:
  type: ClusterIP
  ports:
    - name: "8181"
      port: 8181
      targetPort: 8181
    - name: "8182"
      port: 8182
      targetPort: 8182
  selector:
    app: polaris
