executor: "CeleryExecutor"
# Default airflow tag to deploy
defaultAirflowTag: "3.0.6"
# Airflow version (Used to make some decisions based on Airflow Version being deployed)
airflowVersion: "3.0.6"
apiServer:
  service:
    type: LoadBalancer
webserver:   
  defaultUser:
    enabled: true
    username: airflow
    password: airflow
    role: Admin
config:
  api:
    auth_backends: "airflow.api.auth.backend.basic_auth"

postgresql:
  enabled: false

data:
  metadataConnection:
    user: postgres
    pass: postgres
    protocol: postgresql
    host: postgres
    port: 5432
    db: airflow

dags:
  persistence:
    enabled: true
    existingClaim: opendatalake-dags-pvc
  gitSync:
    enabled: false

logs:
  persistence:
    enabled: true
    existingClaim: opendatalake-logs-pvc

extraEnv: |
  - name: PYTHONPATH
    value: /opt/airflow/dags
  - name: AIRFLOW_CONN_OPENDATALAKE_S3
    value: '{
        "conn_type": "Amazon Web Services",
        "login": "admin",
        "password": "password",
        "host": "opendatalake-minio",
        "port": 9000,
        "extra": {
            "aws_access_key_id": "admin",
            "aws_secret_access_key": "password",
            "endpoint_url": "http://opendatalake-minio:9000",
            "region_name": "us-east-1",
            "aws_allow_http": true,
            "verify": false
        }
    }'
  
  # ECS is not supported in the sandbox, but we add them for partial testing and documentation purpose.
  - name: OPENDATALAKE_ECS_CLUSTER
    value: "ecs-cluster"
  - name: OPENDATALAKE_ECS_SUBNETS
    value: "subnet-123,subnet-456"
  - name: OPENDATALAKE_ECS_SECURITY_GROUPS
    value: "sg-123,sg-456"
  - name: OPENDATALAKE_TASK_OPERATOR_TASK_DEFINITION
    value: "opendatalake-task-def"
  - name: OPENDATALAKE_TASK_OPERATOR_LOG_GROUP
    value: "opendatalake-ecs-logs"
  - name: OPENDATALAKE_TASK_OPERATOR_LOG_REGION
    value: "us-east-1"
  - name: OPENDATALAKE_TASK_OPERATOR_LOG_PREFIX
    value: "opendatalake"
  - name: OPENDATALAKE_SPLICEAI_ACCESS_TOKEN
    value: "<REPLACE_ME_WITH_ACCESS_TOKEN>"

  # Also to test ecs operator (although not needed for compilation). Strangely the boto3 client does not read AWS_REGION
  - name: AWS_DEFAULT_REGION
    value: us-east-1
  - name: AWS_ACCESS_KEY_ID
    value: admin
  - name: AWS_SECRET_ACCESS_KEY
    value: password
